name: shm-streaming

services:
  db:
    container_name: shm_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - shm_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT}:5432

  backend:
    container_name: shm_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    ports:
      - ${DJANGO_PORT}:8000
    depends_on:
      - db

  frontend:
    container_name: shm_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://backend:8000 # Link to backend API
    depends_on:
      - backend

  pgadmin:
    container_name: shm_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80" # pgAdmin will be accessible on port 5050
    depends_on:
      - db
    # networks:
    #   - shmstreaming_net

# networks:
#   shmstreaming_net:
#     driver: bridge

volumes:
  postgres_data: {}
  shm_db_data: {}
