name: shm-streaming

services:
  frontend:
    container_name: shm-streaming-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:8000}
      - DJANGO_SECRET_KEY=${SECRET_KEY:-your_django_secret_key}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - shm-network

  backend:
    container_name: shm-streaming-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8080"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-your_secret_key}
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-shm_db}
      - DB_USER=${DB_USER:-shm_user}
      - DB_PASSWORD=${DB_PASSWORD:-shm_password}
      - WATCHPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true

    depends_on:
      - db
    networks:
      - shm-network

  db:
    container_name: shm-streaming-db
    image: mariadb:latest
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=${DB_NAME:-shm_db}
      - MYSQL_USER=${DB_USER:-shm_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-shm_password}
    networks:
      - shm-network

networks:
  shm-network:
    driver: bridge

volumes:
  mariadb_data:
